title: "Jonas'  Website"
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Jonas Ehrhardt
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed

# Social
social:
  github: https://github.com/j-ehrhardt
  linkedin: https://de.linkedin.com/in/jonas-m-ehrhardt
  google-scholar: https://scholar.google.com/citations?user=lv_VJRgAAAAJ&hl=en
  orchid: https://orcid.org/0000-0001-5023-839X

# Plugins
plugins: 
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
